---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}

library(tidyverse)
library(ggplot2)
library(plotly)

```

```{r}

# Cargamos los tres ficheros csv con los datos de accidentes de los años 2019, 2020 y 2021
accidentes2019 <- read.csv("AccidentesBicicletas_2019.csv", header = T, sep = ";", dec = ".")
accidentes2020 <- read.csv("AccidentesBicicletas_2020.csv", header = T, sep = ";", dec = ".")
accidentes2021 <- read.csv("AccidentesBicicletas_2021.csv", header = T, sep = ";", dec = ".")

# Unimos los datos en un único dataframe
accidentes <- rbind(accidentes2019, accidentes2020, accidentes2021)

# Tranformamos el campo de fecha a tipo date
accidentes <- transform(accidentes, fecha = as.Date(fecha, format =  "%d/%m/%Y"))

# Transformamos el dataset con tres campo:
#     mes
#     año
#     número de accidentes en el mes-año específico
accidentes <- accidentes %>%
  mutate(month = format(accidentes$fecha, "%m"), year = format(accidentes$fecha, "%Y")) %>%
  group_by(month, year) %>%
  summarise(n = n())

```


```{r}

monthly <- accidentes %>%
  mutate(month = as.numeric(month),
         year = factor(unique(year)),
         y = as.numeric(year) - 1 + (month - 1) / 12) 

bars <- monthly %>% 
  mutate(value_norm = n / (max(n) * 1.2),
         xmin = month - 0.5,
         xmax = month + 0.5,
         ymin = y,
         ymax = y + value_norm)
# we could plot `bars` here, but things will not line up nicely, since
# the bar will be nice and flat, but it needs to curve with the spiral.

poly <- bars %>% 
  rowwise() %>% 
  do(with(., data_frame(year = year,
                        month = month,
                        x = c(xmin, xmax, xmax, xmin),
                        y = c(ymin - 1/24, 
                              ymin + 1/24, 
                              ymax + 1/24, 
                              ymax - 1/24))))

ggplot(poly, aes(x, y, fill = interaction(month, year))) + 
  geom_polygon(col = 1) +
  coord_polar() +
  ylim(-3, 3.5) +
  viridis::scale_fill_viridis(discrete = TRUE, option = 'C') +
  scale_x_continuous(breaks = 1:12, labels = month.name) +
  theme_minimal() + 
  theme(legend.position = "none", axis.text.y = element_blank(),
        axis.title = element_blank(),
        panel.background = element_rect(fill = '#eef2f4', colour = '#eef2f4'))
```